sub catch(this as integer)
	shared Exception.Handle as integer

	this = Exception.Handle
end sub
